name: Node setup
description: "Install nodeJS dependencies"
inputs:
  node-version:
    description: 'The version of nodejs'
    required: false
    default: "16"
  package-manager:
    description: 'name of the package manager'
    required: false
    default: "pnpm"
runs:
  using: "composite"
  steps:
    - name: Get code
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: "${{ inputs.node-version }}"
        cache: "${{ inputs.package-manager }}"
    - name: Install dependencies
      shell: bash
      run: pnpm i