name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: Retain days back
        required: true
        default: '30'
        type: string
  schedule:
    - cron: '5 4 * * 1'
# Run weekly, at 04:05 every Monday.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days || 30 }}
